# Site settings
title: Bonnet.pro
email: ludovic@bonnnet.pro
description: > # Ludovic Bonnet, consultant web indépendant depuis 2007.
  Conseil AMOA /AMOE, développement Web et Mobile, Référencement, Infogérance
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bonnet.pro" # the base hostname & protocol for your site

# User setting
owner: Ludovic Bonnet
email: contact@bonnet.pro
skype: lbonnet84
facebook_username: example
linkedin_profile: https://fr.linkedin.com/in/ludovicbonnet
twitter_username: ludobonnet
twitter_username2: ludotech
github_username: ludobonnet
address:
  - line: "Avignon, France"
  # Feel free to add more lines here
telephone: +33 (7) 56 94 56 06
copyright: Ludovic Bonnet

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]
